version: "2.0"

services:

  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
    environment: 
      MONGO_INITDB_DATABASE: advu
    ports:
      - "27017:27017"
    #volumes:
    #  - ./db:/data/db

  nats:
    image: nats
    ports:
      - "4222:4222"

  api:
    build:
      context: .
    #image: ADVuS
      dockerfile: Dockerfile-advus
    env_file: docker-compose.env
    ports:
      - "3000:3000"
    environment:
      SERVICES: api
      PORT: 3000
    links:
      - nats
    depends_on:
      - nats
    

  impressions:
    build:
      context: .
    #image: ADVuS
      dockerfile: Dockerfile-advus
    env_file: docker-compose.env
    environment:
      SERVICES: impressions
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo



  unity:
    build:
      context: .
    #image: ADVuS
      dockerfile: Dockerfile-advus
    env_file: docker-compose.env
    environment:
      SERVICES: unity
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo


  users:
    build:
      context: .
    #image: ADVuS
      dockerfile: Dockerfile-advus
    env_file: docker-compose.env
    environment:
      SERVICES: users
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo

